server:
  port: 9292

spring:
  application:
    name: report-service

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: debug

springdoc:
  show-actuator: true