name: Push branch workflow PR

on:
  push:
    branches:
      - feature/*
      - bugfix/*

jobs:
  build-common-models:
    name: Build common-models and install to local repo
    runs-on: ubuntu-latest

    steps:
# Сборка common-models
      - name: Checkout common-models repository
        uses: actions/checkout@v4.1.7
        with:
          repository: sursindmitry/platform-common-models
          path: common-models

      - name: Set up Java
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build and Test common-models
        working-directory: ./common-models
        run: ./gradlew publishToMavenLocal

# Сборка report-service
      - name: Checkout report-service repository
        uses: actions/checkout@v4.1.7
        with:
          path: report-service

      - name: Build and Test report-service
        working-directory: ./report-service
        run: mvn clean install
